### ISSUE TITLE
different behavier on debug and release mode

### ISSUE THREAD

**Issue by pineapplehunter** [statiolake/proconio-rs#17]
Hi.
I wrote this program.

```rust
use proconio::input;

fn main() {
    input!(x: u32);
    println!("{}", x);
}
```

When I execute the program on debug mode, it prints the output right after I press `Enter`. 
But on release mode it doesn't print when pressing `Enter`, so I have to stop the input with  `^D`.

This issue might not affect use in competitions.

Environment:
* ubuntu 20.10
* rustc 1.49.0

**Comment by statiolake** [comment]
Thank you for opening new issue!

Actually it's an intended behavior. From usability point of view, it's better to process a line as soon as Enter key is pressed. However, regarding to the runtime speed, reading all input until EOF at once is a bit faster than line-by-line method. To achieve optimal behavior in most cases, I decided to be more user-friendly in a debug build and to focus on the speed in a release build. For more detailed explanation see <https://docs.rs/proconio/0.4.1/proconio/source/index.html>.

As you said, this shouldn't behave differently between the local and the server (except interactive problems, where you need to explicitly specify line-by-line method and such a usage is also covered in the above reference URL). If you find the case where it does affect the verdict, please file a new issue here.

**Comment by pineapplehunter** [comment]
Now I understand.
It wasn't very obvious at first but that makes sense.
Thanks!
