### ISSUE TITLE
Add something like `input_interactive!`

### ISSUE THREAD

**Issue by statiolake** [statiolake/proconio-rs#26]
For interactive problem, `OnceSource` won't work as expected. To use proconio in such problems we need to explicitly specify `LineSource` for the source of `input!`. Preparing a macro that always uses `LineSource` may be helpful.

**Comment by SaiYS** [comment]
I think this feature is helpful for especially users who is not familiar with proconio's internal implementation.
I would like to work on this, may I create a PR for you?

**Comment by statiolake** [comment]
Of course :) Thanks.
