### ISSUE TITLE
Conflict once_cell freeze version (AtCoder 2023/01 language environment)

### ISSUE THREAD

**Issue by mizar** [statiolake/proconio-rs#43]
There is a conflict between proconio 0.4.4 and the proposed AtCoder 2023/01 language update environment, which tries to freeze different versions of once_cell.

- https://github.com/statiolake/proconio-rs/pull/38
```toml
once_cell = "=1.14.0"
```
- https://github.com/qryxip/proposal-for-atcoder-language-update/blob/main/Cargo.toml#L16
```toml
once_cell = "=1.17.1"
```

**Comment by qryxip** [comment]
Why not replace it with [`std::sync::OnceLock`](https://doc.rust-lang.org/stable/std/sync/struct.OnceLock.html)?

<https://rust-lang-jp.zulipchat.com/#narrow/stream/334326-.E7.AB.B6.E3.83.97.E3.83.AD/topic/AtCoder.E8.A8.80.E8.AA.9E.E3.82.A2.E3.83.83.E3.83.97.E3.83.87.E3.83.BC.E3.83.88.282023.E5.B9.B4.29/near/367320251>
